include ../Makefile.include

all:
	$(FSTAR) Incr.fst
	$(FSTAR) Sum.fst
	$(FSTAR) RefinedStack.fst
	$(FSTAR) RefinedStackClient.fst
	$(FSTAR) SumST.fst
	$(FSTAR) InitFreezeMST.fst

clean:
	rm -dfr *~ *.exe out
