ALL_C_FILES=C_Loops_Spec_Loops.c BufferAlloc.c LowStar_BufferOps.c LowStar_ModifiesPat.c LowStar_Modifies.c FStar.c LowStar_Buffer.c Prims.c
ALL_H_FILES=C_Loops_Spec_Loops.h BufferAlloc.h LowStar_BufferOps.h LowStar_ModifiesPat.h LowStar_Modifies.h FStar.h LowStar_Buffer.h Prims.h
